### PR TITLE
Fixed #256: revised search-ctrl init logic, allowed relative url in News section

### LINKED ISSUE #256: Problems with adding links in the News section
The links aren't working properly to a filtered search. Try the last link in the news section that is currently available. If you click on Next or 2 the pagination box redraws. When you first land on the page, it appears as if it is listing everything.

### PR DESCRIPTION
**Pull request by grtjn**
#256

### CODE REVIEW

**Comment by joemfb** [comment]
Question: what are the customizations to ml-search-ng that require it to be checked in?

**Comment by grtjn** [comment]
There should be a comment in index.html. I considered upgrading to latest ml-search, but that requires angular 0.14. Is there a version if ml-search that works with 0.13?

**Comment by joemfb** [comment]
`ml-search-ng@0.2.4` upgraded the angular dependency to `^1.4.1`. I believe I did that for the update to the `$q` promise implementation (which provides API compat with the native `Promise`). Do you know if there's anything preventing `demo-cat` from upgrading angular?

**Comment by grtjn** [comment]
Nothing but proper testing? I'd prefer doing that separately though. I encourage you to open a ticket for it. I completely forgot about copying and patching ml-search. I think it was just for something small..

**Pull request merged**
